### ISSUE TITLE
RPC Server memoize("fib") at wrong location

### ISSUE THREAD

**Issue by error756** [oylenshpeegul/RabbitMQ-Tutorial-Perl#1]
Hi Tim

In the RPC server script, the memoize'ation should be ahead of the call if I am not mistaken.
With the current location in #40, it doesn't seem to be caching properly.
But moved into line #8 makes a big difference.
(Tested with 5.18)

Regards,
Marcel

**Comment by oylenshpeegul** [comment]
Thanks, Marcel!

I guess a smarter implementation of fib would be better, but a naïve fib with caching works well enough.

Thanks again!
